 # Get editor completions based on the config schema  
"$schema" = 'https://starship.rs/config-schema.json'  
  
# Inserts a blank line between shell prompts  
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true
  
# Set the continuation prompt to "▶▶"  
continuation_prompt = "▶▶"

# Assigning symbols in prompt
[character]                         # The name of the module we are configuring is "character"
success_symbol = "[❯](bold green)"  # The "success_symbol" is set to "➜" with color "bold green"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[V](bold green) "