# ~/.config/starship.toml

# Get editor completions based on the config schema  
"$schema" = 'https://starship.rs/config-schema.json'  

# -----------------------------------------
# General Prompt Configuration
# -----------------------------------------
add_newline = false               # Inserts a blank line between shell prompts  
format = """
$shell\
$directory\
$git_branch$git_status\
$nodejs\
$ruby\
$python\
$rust\
$golang\
$time\
$character
"""

# -----------------------------------------
# Shell Identification Module
# -----------------------------------------
[shell]
# Displays the current shell (bash, zsh, fish, nu, elvish, etc.)
disabled = false

# Format of the shell display
format = "[$indicator]($style) "
style = "bold cyan"

# Customize symbols for each shell
bash_indicator = "ÓØä bash"
zsh_indicator = "Ôíâ zsh"
fish_indicator = "Û∞à∫ fish"
powershell_indicator = "ÓØá pwsh"
ion_indicator = "‚öôÔ∏è ion"
elvish_indicator = "‚ú® elvish"
tcsh_indicator = "tcsh"
xonsh_indicator = "üß¨ xonsh"
cmd_indicator = "ÓØÑ cmd"
nu_indicator = "Û∞û∑ nu"

# -----------------------------------------
# Directory Module
# -----------------------------------------
[directory]
truncation_length = 3
style = "bold blue"

# -----------------------------------------
# Git Module
# -----------------------------------------
[git_branch]
symbol = "Ôêò "
style = "purple"

[git_status]
style = "yellow"

# -----------------------------------------
# Programming Language Modules
# -----------------------------------------
[nodejs]
symbol = "Û∞éô "
style = "green"

[python]
symbol = "ÓòÜ "
style = "green"

[rust]
symbol = "Óû® "
style = "red"

[golang]
symbol = "Û∞üì "
style = "cyan"

# -----------------------------------------
# Time Module
# -----------------------------------------
[time]
disabled = true
time_format = "%H:%M"        # see below for various time format
style = "bold white"
format = "[$time]($style) "

# --------------------
# Command duration
# --------------------
[cmd_duration]
min_time = 2000               # Show if command takes > 2 seconds
format = "took [$duration](bold yellow)"
show_milliseconds = true

# -----------------------------------------
# Prompt Character
# -----------------------------------------
[character]
# success_symbol = "[‚ûú](bold green)"
success_symbol = "[‚ùØ](bold green)"
error_symbol = "[‚úó](bold red)"
vicmd_symbol = "[V](bold green) "

# Set the continuation prompt to "‚ñ∂‚ñ∂"  
#continuation_prompt = "‚ñ∂‚ñ∂"     


# Make prompt a single line instead of two lines
[line_break]
disabled = true


#Set time format 
#"%H:%M"  ‚Üí 19:32
#"%I:%M %p"  ‚Üí 07:32 PM 
#"%I:%M:%S %p"  ‚Üí 07:32:15 PM  
#| "%l:%M %p"  ‚Üí 7:32 PM (no leading zero)